### ISSUE TITLE
[Request] Algorithmic teleporting

### ISSUE THREAD

**Issue by mn1213** [Qballl/WildernessTp#60]
In addition to random teleportation, I think it would be fantastic if this plugin could send you to a more predictable spot in the wilderness, like along a spiral. Invalid/occupied spots could be cached for a while for performance.

To illustrate, I've come up with a couple Javascript examples at https://jsfiddle.net/4m3qahjn/. They operate within set bounds (i.e. world size) with configurable distance between points and a dead zone (like around spawn), and should be fairly easy to drop in to your existing code.

**Comment by RonaldBunk** [comment]
As of R4 (v4.0.0) we've added the ability to use 'filters' for generating locations. If you want, you're free to implement your idea, on your own.

Though, if you'd implement it, you're free to make a pull-request (Just make sure you'll create a pull-request for the branch 4.0 specifically, as 3.0 is completely different and no so extensive.). Also we'll be giving support if desired (Though v3- is Qball's department, I am more about v4+).

I am mainly saying this because I don't think it's that of a benefit to implement your suggestion.

**Comment by RonaldBunk** [comment]
@Qballl Close please. :)
